### ISSUE TITLE
Error en (SQL: alter table `users` add unique `users_email_unique`(`email`))

### ISSUE THREAD

**Issue by JulianBeytia** [CarlosUh/triciseguro#10]
![image](https://user-images.githubusercontent.com/51243734/77191145-2073e800-6aa0-11ea-8e27-54313b9cad6c.png)

**Comment by CarlosUh** [comment]
Agrega la linea como se presenta en la siguiente imagen
![image](https://user-images.githubusercontent.com/299425/77191652-e1926200-6aa0-11ea-9818-bee905350707.png)
